require("user.options")
require("user.keymaps")
require("user.packages")
require("config.autopairs")
require("config.bufferline")
require("config.cmpConfig")
require("config.statusbar")
require("config.treesitter")
